=== fabricejumel/lirec/libs/cmion/cmionLauncher/CompetencyManagerRules.dtd
<!--Top Element of the competency manager rules file -->
<!ELEMENT CompetencyManagerRules (Rule*)>

<!--A  rule for the competency manager, consisting of a mind action and a competency execution plan-->
<!ELEMENT Rule (MindAction,CompetencyExecutionPlan)>

<!--The  Mind Action part of the rule: whenever a mind action occurs while running the application that matches
 the action described here, the competency execution part of the rule is considered as a candidate for
 realizing the execution of that action-->
<!ELEMENT MindAction (Parameter*)>
<!--The name of the action, has to match the name of the occurring action, or can be * to match any action-->
<!ATTLIST MindAction Name CDATA #REQUIRED>

<!--To be considered a match, all parameters have to match and the rule must specify as many parameters as
 the occurring action -->
<!ELEMENT Parameter EMPTY>
<!-- The  number of the parameter, starts counting at 1-->
<!ATTLIST Parameter No CDATA #REQUIRED>
<!--The value of the parameter, needs to match the value of occurring parameter or can be * to match any value-->
<!ATTLIST Parameter Value CDATA #REQUIRED>

<!--A sequence of competencies to be executed by the competency execution system-->
<!ELEMENT CompetencyExecutionPlan (Competency*)>

<!--A  competency executed as a step of the competency execution plan -->
<!ELEMENT Competency (CompetencyParameter*)>
<!--the ID of the competency (needs to be a unique value amongst all competencies defined within one plan-->
<!ATTLIST Competency ID CDATA #REQUIRED>
<!--the type of the competency, this must correspond to the type of a competency in the competency library
otherwise this step of the plan cannot be executed-->
<!ATTLIST Competency Type CDATA #REQUIRED>
<!--an (optional) comma seperated list of IDs of other competencies within the same plan indicating the 
competencies this competency is dependent on. This competency will not be executed until all dependent
competencies have executed successfully. At least one competency within each plan must not have
any dependencies. Competencies in the same plan that have the same dependencies are executed
in parallel, if they are executed.-->
<!ATTLIST Competency Dependency CDATA #IMPLIED>

<!--A parameter that can be passed to the competency when it is executed-->
<!ELEMENT CompetencyParameter EMPTY>
<!--the name  of the parameter-->
<!ATTLIST CompetencyParameter Name CDATA #REQUIRED>
<!--the value of the parameter, can also be the mind action subject, name or any of its parameters 
 by putting $subject, $action, $parameter1, $parameter2, etc. -->
<!ATTLIST CompetencyParameter Value CDATA #REQUIRED>

=== fabricejumel/lirec/scenarios/InTheWild/cmionInTheWild/CompManagerRulesVirtEmys.xml
<?xml version="1.0" ?>
<!DOCTYPE CompetencyManagerRules SYSTEM "CompetencyManagerRules.dtd">

<CompetencyManagerRules>

	
	<Rule>
		
		<MindAction Name="askForID">
				<Parameter No="1" Value="*" />				
		</MindAction>		
		
		<CompetencyExecutionPlan>
			<Competency ID="1" Type="TTS">
			 <CompetencyParameter Name="text" Value="Hello my Name is Sarah. Who are you? I cannot tell. But you can send me an SMS to tell me." />
			</Competency>
		</CompetencyExecutionPlan>

	</Rule>
	
	<Rule>
	
		<MindAction Name="welcomeUnknown">
				<Parameter No="1" Value="*" />
		</MindAction>			
		<CompetencyExecutionPlan>
			<Competency ID="1" Type="TTS">
			 <CompetencyParameter Name="text" Value="Howdy $parameter1. I cannot talk with you. I'm busy. I'm waiting for someone and it's not you. Please go away now and leave me to my important task. " />
			</Competency>
		</CompetencyExecutionPlan>

	</Rule>
	
	<Rule>

		<MindAction Name="welcomeGuest">
				<Parameter No="1" Value="*" />
		</MindAction>			
		<CompetencyExecutionPlan>
			<Competency ID="1" Type="TTS">
			 <CompetencyParameter Name="text" Value="Nice to meet you $parameter1. I was expecting you." />
			</Competency>
		</CompetencyExecutionPlan>

	</Rule>
	
	<Rule>

		<MindAction Name="offerDirections">
				<Parameter No="1" Value="*" />
		</MindAction>			
		<CompetencyExecutionPlan>
			<Competency ID="1" Type="TTS">
			 <CompetencyParameter Name="text" Value="Do you want me to direct you to the lab?" />
			</Competency>
			<Competency ID="2" Type="EmysAskBinaryQuestion" Dependency="1">
			 <CompetencyParameter Name="choice1" Value="yes" />
			 <CompetencyParameter Name="choice2" Value="no" />
			 <CompetencyParameter Name="question" Value="offerDirections" />
			 <CompetencyParameter Name="person" Value="$parameter1" />			 
			</Competency>
		</CompetencyExecutionPlan>
	</Rule>

	<Rule>

		<MindAction Name="giveDirections">
				<Parameter No="1" Value="*" />
		</MindAction>	
		<CompetencyExecutionPlan>
			<Competency ID="1" Type="TTS">
			 <CompetencyParameter Name="text" Value="The lab number is 2 22. It is on the second corridor. Go up the stairs to the second floor, turn left, follow the corridor and turn left again at the next junction. The lab will be in the corridor to your left." />
			</Competency>
		</CompetencyExecutionPlan>

	</Rule>
	
	<Rule>

		<MindAction Name="giveNoDirections">
				<Parameter No="1" Value="*" />
		</MindAction>			
		<CompetencyExecutionPlan>
			<Competency ID="1" Type="TTS">
			 <CompetencyParameter Name="text" Value="Very well, I guess you have been here before." />
			</Competency>
		</CompetencyExecutionPlan>

	</Rule>
	

	
	<Rule>

		<MindAction Name="askMigrateToPhone">
				<Parameter No="1" Value="*" />
		</MindAction>			
		<CompetencyExecutionPlan>
			<Competency ID="1" Type="TTS">
			 <CompetencyParameter Name="text" Value="Do you want me to migrate to your phone and show you the way?" />
			</Competency>
			<Competency ID="2" Type="EmysAskBinaryQuestion" Dependency="1">
			 <CompetencyParameter Name="choice1" Value="yes" />
			 <CompetencyParameter Name="choice2" Value="no" />
			 <CompetencyParameter Name="question" Value="askMigrateToPhone" />
			 <CompetencyParameter Name="person" Value="$parameter1" />			 
			</Competency>
		</CompetencyExecutionPlan>
		
	</Rule>

	<Rule>

		<MindAction Name="migrate">
				<Parameter No="1" Value="Phone" />
		</MindAction>			
		<CompetencyExecutionPlan>
			<Competency ID="1" Type="TTS">
			 <CompetencyParameter Name="text" Value="I'm transferring over to your phone now. Watch This." />
			</Competency>
			<Competency ID="2" Type="Migration" Dependency="1">
			 <CompetencyParameter Name="DeviceName" Value="Phone" />
			</Competency>
		</CompetencyExecutionPlan>
	
	</Rule>
	
	<Rule>
		
		<MindAction Name="migrate">
			<Parameter No="1" Value="Robot" />
		</MindAction>			
		<CompetencyExecutionPlan>
			<Competency ID="1" Type="TTS">
			 <CompetencyParameter Name="text" Value="OK. I'm going home to my robot body. See you there in a minute." />
			</Competency>
			<Competency ID="2" Type="Migration" Dependency="1">
			 <CompetencyParameter Name="DeviceName" Value="Robot" />
			</Competency>
		</CompetencyExecutionPlan>
		
	</Rule>

	<Rule>
		
		<MindAction Name="wozTalk">
			<Parameter No="1" Value="*" />
		</MindAction>			
		<CompetencyExecutionPlan>
			<Competency ID="1" Type="VirtualEmys">
			  <CompetencyParameter Name="Command" Value="SetSubtitle" />
			  <CompetencyParameter Name="Subtitle" Value="$parameter1" />
			</Competency>
			<Competency ID="2" Type="SimpleTalk" Dependency="1">
			  <CompetencyParameter Name="text" Value="$parameter1" />
			</Competency>
			<Competency ID="3" Type="VirtualEmys" Dependency="2">
			  <CompetencyParameter Name="Command" Value="RemoveSubtitle" />
			</Competency>
		</CompetencyExecutionPlan>
		
	</Rule>

	<Rule>
		
		<MindAction Name="wozEmotion">
			<Parameter No="1" Value="*" />
		</MindAction>			
		<CompetencyExecutionPlan>
			<Competency ID="1" Type="SimpleAnimation">
			 <CompetencyParameter Name="animation" Value="$parameter1" />
			</Competency>
		</CompetencyExecutionPlan>
		
	</Rule>

	<Rule>
		
		<MindAction Name="wozEmotionNoWait">
			<Parameter No="1" Value="*" />
		</MindAction>			
		<CompetencyExecutionPlan>
			<Competency ID="1" Type="SimpleAnimation">
			 <CompetencyParameter Name="animation" Value="$parameter1" />
			 <CompetencyParameter Name="returnImmediately" Value="true" />
			</Competency>
		</CompetencyExecutionPlan>
		
	</Rule>

	<Rule>
		<MindAction Name="wozQuestion">
			<Parameter No="1" Value="*" />
		</MindAction>			
		<CompetencyExecutionPlan>
			<Competency ID="1" Type="EmysAskQuestion">
			 <CompetencyParameter Name="choice1" Value="$parameter1" />
 			 <CompetencyParameter Name="question" Value="question" />
 			 <CompetencyParameter Name="person" Value="wizard" /> 			 
			</Competency>
		</CompetencyExecutionPlan>		
	</Rule>


	<Rule>	
		<MindAction Name="wozQuestion">
			<Parameter No="1" Value="*" />
			<Parameter No="2" Value="*" />
		</MindAction>			
		<CompetencyExecutionPlan>
			<Competency ID="1" Type="EmysAskQuestion">
			 <CompetencyParameter Name="choice1" Value="$parameter1" />
			 <CompetencyParameter Name="choice2" Value="$parameter2" />
 			 <CompetencyParameter Name="question" Value="question" />
 			 <CompetencyParameter Name="person" Value="wizard" /> 			 
			</Competency>
		</CompetencyExecutionPlan>
	</Rule>

	<Rule>	
		<MindAction Name="wozQuestion">
			<Parameter No="1" Value="*" />
			<Parameter No="2" Value="*" />
			<Parameter No="3" Value="*" />
		</MindAction>			
		<CompetencyExecutionPlan>
			<Competency ID="1" Type="EmysAskQuestion">
			 <CompetencyParameter Name="choice1" Value="$parameter1" />
			 <CompetencyParameter Name="choice2" Value="$parameter2" />
			 <CompetencyParameter Name="choice3" Value="$parameter3" />
 			 <CompetencyParameter Name="question" Value="question" />
 			 <CompetencyParameter Name="person" Value="wizard" /> 			 
			</Competency>
		</CompetencyExecutionPlan>
	</Rule>
	
	<Rule>	
		<MindAction Name="wozQuestion">
			<Parameter No="1" Value="*" />
			<Parameter No="2" Value="*" />
			<Parameter No="3" Value="*" />
			<Parameter No="4" Value="*" />
		</MindAction>			
		<CompetencyExecutionPlan>
			<Competency ID="1" Type="EmysAskQuestion">
			 <CompetencyParameter Name="choice1" Value="$parameter1" />
			 <CompetencyParameter Name="choice2" Value="$parameter2" />
			 <CompetencyParameter Name="choice3" Value="$parameter3" />
			 <CompetencyParameter Name="choice4" Value="$parameter4" />
 			 <CompetencyParameter Name="question" Value="question" />
 			 <CompetencyParameter Name="person" Value="wizard" /> 			 
			</Competency>
		</CompetencyExecutionPlan>
	</Rule>

	<Rule>	
		<MindAction Name="wozCancelQuestion">
		</MindAction>			
		<CompetencyExecutionPlan>
			<Competency ID="1" Type="VirtualEmys">
			 <CompetencyParameter Name="Command" Value="CancelQuestion" />
			</Competency>
		</CompetencyExecutionPlan>
	</Rule>

	<Rule>	
		<MindAction Name="wozSetVisible">
		</MindAction>			
		<CompetencyExecutionPlan>
			<Competency ID="1" Type="VirtualEmys">
			 <CompetencyParameter Name="Command" Value="SetVisible" />
			</Competency>
		</CompetencyExecutionPlan>
	</Rule>

	<Rule>	
		<MindAction Name="wozSetInvisible">
		</MindAction>			
		<CompetencyExecutionPlan>
			<Competency ID="1" Type="VirtualEmys">
			 <CompetencyParameter Name="Command" Value="SetInvisible" />
			</Competency>
		</CompetencyExecutionPlan>
	</Rule>
	
	<Rule>
		
		<MindAction Name="wozGaze">
			<Parameter No="1" Value="*" />
		</MindAction>			
		<CompetencyExecutionPlan>
			<Competency ID="1" Type="EmysGaze">
			 <CompetencyParameter Name="gazeTarget" Value="$parameter1" />
			</Competency>
		</CompetencyExecutionPlan>
		
	</Rule>
	
	<Rule>
		
		<MindAction Name="testbug">
			<Parameter No="1" Value="*" />
		</MindAction>			
		<CompetencyExecutionPlan>
			<Competency ID="1" Type="SimpleAnimation">
			 <CompetencyParameter Name="animation" Value="Anger5" />
			</Competency>
			<Competency ID="2" Type="VirtualEmys">
			 <CompetencyParameter Name="Command" Value="SetVisible" />
			</Competency>
			<Competency ID="3" Type="SimpleAnimation" Dependency = "2">
			 <CompetencyParameter Name="animation" Value="Joy5" />
			</Competency>
		</CompetencyExecutionPlan>
		
	</Rule>	
	
	<Rule>
		
		<MindAction Name="greet">
			<Parameter No="1" Value="*" />
		</MindAction>			
		<CompetencyExecutionPlan>
			<Competency ID="1" Type="TestType7">
			</Competency>
		</CompetencyExecutionPlan>
		
	</Rule>
	
</CompetencyManagerRules>

=== fabricejumel/lirec/libs/cmion/cmionLauncher/CompManagerRulesPhone.xml
<?xml version="1.0" ?>
<!DOCTYPE CompetencyManagerRules SYSTEM "CompetencyManagerRules.dtd">

<CompetencyManagerRules>
	


	<Rule>
		
		<MindAction Name="DeliverPhoneTo">
				<Parameter No="1" Value="*" />
		</MindAction>		
		
		<CompetencyExecutionPlan>
			
			<Competency ID="1" Type="MoveTo">
				<CompetencyParameter Name="Target" Value="$parameter1" />
			</Competency>
			
			<Competency ID="2" Type="PhoneSensor" >
				<CompetencyParameter Name="PickedUp" Value="True" />
			</Competency>
			
			<Competency ID="3" Type="PhoneSensor" Dependency ="2" >
				<CompetencyParameter Name="PickedUp" Value="False" />
			</Competency>
			
			<Competency ID="4" Type="MoveTo" Dependency ="3" >
				<CompetencyParameter Name="Target" Value="Home" />
			</Competency>
			
			
		</CompetencyExecutionPlan>
		
	</Rule>

</CompetencyManagerRules>

=== fabricejumel/lirec/scenarios/InTheWild/cmionInTheWild/CompManagerRulesInTheWild.xml
<?xml version="1.0" ?>
<!DOCTYPE CompetencyManagerRules SYSTEM "CompetencyManagerRules.dtd">

<CompetencyManagerRules>

	<Rule>
		
		<MindAction Name="sendSMS">
				<Parameter No="1" Value="*" />
				<Parameter No="2" Value="*" />				
		</MindAction>

		<CompetencyExecutionPlan>
			<Competency ID="1" Type="SMSSender">
			 <CompetencyParameter Name="To" Value="$parameter1" />
			 <CompetencyParameter Name="Content" Value="$parameter2" />			 
			</Competency>

		</CompetencyExecutionPlan>

	</Rule>
	
	<Rule>
		
		<MindAction Name="talk">
				<Parameter No="1" Value="*" />
				<!--<Parameter No="2" Value="*" /> -->
		</MindAction>		
		
		<CompetencyExecutionPlan>
			<Competency ID="1" Type="GretaBMLCreator">
			 <CompetencyParameter Name="Type" Value="talk" />
			 <CompetencyParameter Name="Text" Value="$parameter1" />			 
			 <CompetencyParameter Name="BmlOutName" Value="bmlVar" />
			</Competency>

			<Competency ID="2" Type="GretaBMLSender" Dependency="1">
			 <CompetencyParameter Name="BmlInName" Value="bmlVar" />
			</Competency>
		</CompetencyExecutionPlan>
		
	</Rule>

	<Rule>
		
		<MindAction Name="gesture">
				<Parameter No="1" Value="*" />
				<Parameter No="2" Value="*" />
				<Parameter No="3" Value="*" />
		</MindAction>		
		
		<CompetencyExecutionPlan>
			<Competency ID="1" Type="GretaBMLCreator">
			 <CompetencyParameter Name="Type" Value="gesture" />
			 <CompetencyParameter Name="GestureName" Value="$parameter1" />			 
			 <CompetencyParameter Name="GestureClass" Value="$parameter2" />			 
			 <CompetencyParameter Name="GestureType" Value="$parameter3" />			 
			 <CompetencyParameter Name="BmlOutName" Value="bmlVar" />
			</Competency>

			<Competency ID="2" Type="GretaBMLSender" Dependency="1">
			 <CompetencyParameter Name="BmlInName" Value="bmlVar" />
			</Competency>
		</CompetencyExecutionPlan>
		
	</Rule>
	
	<Rule>
		
		<MindAction Name="emotion">
				<Parameter No="1" Value="*" />
		</MindAction>		
		
		<CompetencyExecutionPlan>
			<Competency ID="1" Type="GretaBMLCreator">
			 <CompetencyParameter Name="Type" Value="emotion" />
			 <CompetencyParameter Name="Emotion" Value="$parameter1" />			 
			 <CompetencyParameter Name="BmlOutName" Value="bmlVar" />
			</Competency>

			<Competency ID="2" Type="GretaBMLSender" Dependency="1">
			 <CompetencyParameter Name="BmlInName" Value="bmlVar" />
			</Competency>
		</CompetencyExecutionPlan>
		
	</Rule>
	
		<Rule>
		
		<MindAction Name="gaze">
				<Parameter No="1" Value="*" />
		</MindAction>		
		
		<CompetencyExecutionPlan>
			<Competency ID="1" Type="GretaBMLCreator">
			 <CompetencyParameter Name="Type" Value="gaze" />
			 <CompetencyParameter Name="Direction" Value="$parameter1" />			 
			 <CompetencyParameter Name="BmlOutName" Value="bmlVar" />
			</Competency>

			<Competency ID="2" Type="GretaBMLSender" Dependency="1">
			 <CompetencyParameter Name="BmlInName" Value="bmlVar" />
			</Competency>
		</CompetencyExecutionPlan>
		
	</Rule>
	

	
</CompetencyManagerRules>

=== fabricejumel/lirec/libs/cmion/cmionLauncher/CompManagerRulesTeamBuddy.xml
<?xml version="1.0" ?>
<!DOCTYPE CompetencyManagerRules SYSTEM "CompetencyManagerRules.dtd">

<CompetencyManagerRules>
	

	<!-- this is a set of rules for testing the competency execution system,
	 uses the competencies in package cmionTeamBuddy\src\cmion.TeamBuddy.competencies.* -->


	<!-- Rule 1: In this plan, the robot should approach the user and greet the user when it is close
				enough to the user. The plan is initiated when the robot finds a face and a mind action
				"greet" is passed from FAtiMA -->
		 
	<Rule>
		
		<MindAction Name="greet">
				<Parameter No="1" Value="*" />
		</MindAction>		
		
		<!-- Plan 1: geared towards a robot embodiment -->
		<CompetencyExecutionPlan>
			
			<Competency ID="1" Type="MoveToUser">
			</Competency>
			
			<!-- Speak is active only when MoveToUser is finished, so Dependency="1" -->
			<Competency ID="2" Type="Speak" Dependency="1">
			</Competency>
			
		</CompetencyExecutionPlan>
		
	</Rule>
	
	
	
	<Rule>
		
		
		<MindAction Name="greetwithBML">
				<Parameter No="1" Value="*" />
		</MindAction>		
		
		<!-- Plan 1: geared towards a robot embodiment -->
		<CompetencyExecutionPlan>
			<Competency ID="1" Type="MoveToUser">
			</Competency>
			<Competency ID="2" Type="GretaBMLCreator">
			 <CompetencyParameter Name="Type" Value="emotion" />
			 <CompetencyParameter Name="Emotion" Value="joy" />			 
			 <CompetencyParameter Name="BmlOutName" Value="bmlVar" />
			</Competency>
			<Competency ID="3" Type="GretaBMLSender" Dependency="2">
			 <CompetencyParameter Name="BmlInName" Value="bmlVar" />
			</Competency>
			<Competency ID="4" Type="GretaBMLCreator" Dependency="3">
			 <CompetencyParameter Name="Type" Value="talk" />
			 <CompetencyParameter Name="Text" Value="Hello my name is Sarah" />			 
			 <CompetencyParameter Name="BmlOutName" Value="bmlVar" />
			</Competency>

			<Competency ID="5" Type="GretaBMLSender" Dependency="1,4">
			 <CompetencyParameter Name="BmlInName" Value="bmlVar" />
			</Competency>
		</CompetencyExecutionPlan>

		
	</Rule>
	
	
	<Rule>
		
		<MindAction Name="TestAction">
				<Parameter No="1" Value="test" />
		</MindAction>		
		
		<CompetencyExecutionPlan>
			<Competency ID="1" Type="TestType1">
			</Competency>
		</CompetencyExecutionPlan>
		
	</Rule>

	<!-- Rule 2: this plan should not be tried by competency manager, because although
		it is more specific than plan 3, in our test case the parameter will not match -->

	<Rule>
		
		<MindAction Name="TestAction">
				<Parameter No="1" Value="someValueThatWillNotMatch" />
		</MindAction>		
		
		<CompetencyExecutionPlan>
			<Competency ID="1" Type="TestType4">
			</Competency>
		</CompetencyExecutionPlan>
		
	</Rule>


	<!-- Rule 3: this plan should be tried by competency manager after above fails -->

	<Rule>
			
		<MindAction Name="TestAction">
				<Parameter No="1" Value="*" />
		</MindAction>		
		
		<CompetencyExecutionPlan>
			<Competency ID="1" Type="TestType2">
			     <CompetencyParameter Name="RandomOutName" Value="$parameter1" />
			</Competency>

			<Competency ID="2" Type="TestType3" Dependency="1">
			     <CompetencyParameter Name="RandomInName" Value="$parameter1" />
			</Competency>
		</CompetencyExecutionPlan>
		
	</Rule>
	
	<!-- Rule 4: this is the rule for testing the second mind action,  -->

	<Rule>
			
		<MindAction Name="TestAction2">
		</MindAction>		
		
		<CompetencyExecutionPlan>
			<Competency ID="1" Type="TestType4">
			</Competency>
		</CompetencyExecutionPlan>
		
	</Rule>
	
	
	<Rule>
		
		<MindAction Name="talk">
				<Parameter No="1" Value="*" />
				<Parameter No="2" Value="*" />
		</MindAction>		
		
		<CompetencyExecutionPlan>
			<Competency ID="1" Type="GretaBMLCreator">
			 <CompetencyParameter Name="Type" Value="talk" />
			 <CompetencyParameter Name="Text" Value="$parameter1" />			 
			 <CompetencyParameter Name="Emotion" Value="$parameter2" />			 
			 <CompetencyParameter Name="BmlOutName" Value="bmlVar" />
			</Competency>

			<Competency ID="2" Type="GretaBMLSender" Dependency="1">
			 <CompetencyParameter Name="BmlInName" Value="bmlVar" />
			</Competency>
		</CompetencyExecutionPlan>
		
	</Rule>

	<Rule>
		
		<MindAction Name="gesture">
				<Parameter No="1" Value="*" />
				<Parameter No="2" Value="*" />
				<Parameter No="3" Value="*" />
		</MindAction>		
		
		<CompetencyExecutionPlan>
			<Competency ID="1" Type="GretaBMLCreator">
			 <CompetencyParameter Name="Type" Value="gesture" />
			 <CompetencyParameter Name="GestureName" Value="$parameter1" />			 
			 <CompetencyParameter Name="GestureClass" Value="$parameter2" />			 
			 <CompetencyParameter Name="GestureType" Value="$parameter3" />			 
			 <CompetencyParameter Name="BmlOutName" Value="bmlVar" />
			</Competency>

			<Competency ID="2" Type="GretaBMLSender" Dependency="1">
			 <CompetencyParameter Name="BmlInName" Value="bmlVar" />
			</Competency>
		</CompetencyExecutionPlan>
		
	</Rule>
	
	<Rule>
		
		<MindAction Name="emotion">
				<Parameter No="1" Value="*" />
		</MindAction>		
		
		<CompetencyExecutionPlan>
			<Competency ID="1" Type="GretaBMLCreator">
			 <CompetencyParameter Name="Type" Value="emotion" />
			 <CompetencyParameter Name="Emotion" Value="$parameter1" />			 
			 <CompetencyParameter Name="BmlOutName" Value="bmlVar" />
			</Competency>

			<Competency ID="2" Type="GretaBMLSender" Dependency="1">
			 <CompetencyParameter Name="BmlInName" Value="bmlVar" />
			</Competency>
		</CompetencyExecutionPlan>
		
	</Rule>
	

	


</CompetencyManagerRules>

=== fabricejumel/lirec/libs/cmion/cmionLauncher/CompManagerRulesInTheWild.xml
<?xml version="1.0" ?>
<!DOCTYPE CompetencyManagerRules SYSTEM "CompetencyManagerRules.dtd">

<CompetencyManagerRules>
		<Rule>
		
		<MindAction Name="TestAction">
				<Parameter No="1" Value="test" />
		</MindAction>		
		
		<CompetencyExecutionPlan>
			<Competency ID="1" Type="GretaBMLCreator">
			 <CompetencyParameter Name="BmlOutName" Value="bmlVar" />
			</Competency>

			<Competency ID="2" Type="GretaBMLSender" Dependency="1">
			 <CompetencyParameter Name="BmlInName" Value="bmlVar" />
			</Competency>

		</CompetencyExecutionPlan>
		
	</Rule>
	
</CompetencyManagerRules>
