=== fabricejumel/lirec/libs/cmion/cmionLauncher/WorldModelInit.dtd
<!-- Main element of architecture configuration file-->
<!ELEMENT WorldModel (Agent|Object)*>

<!--an agent on the world model-->
<!ELEMENT Agent (Property)*>
<!--the name of the agent-->
<!ATTLIST Agent Name CDATA #REQUIRED>

<!--an object on the world model-->
<!ELEMENT Object (Property)*>
<!--the name of the agent-->
<!ATTLIST Object Name CDATA #REQUIRED>

<!--a property of an agent or object-->
<!ELEMENT Property EMPTY>
<!--the name of the property-->
<!ATTLIST Property Name CDATA #REQUIRED>
<!--the value of the property-->
<!ATTLIST Property Value CDATA #REQUIRED>
<!--whether the property is persistent-->
<!ATTLIST Property Persistent CDATA #IMPLIED>

=== fabricejumel/lirec/libs/cmion/cmionLauncher/worldModelInit.xml
<!DOCTYPE WorldModel SYSTEM "WorldModelInit.dtd">
<WorldModel>
	<Agent Name="UserA">
		<Property Name = "speaksEnglish" Value="True"/>
		<Property Name = "speaksChinese" Value="False"/>		
	</Agent>
	
	<Agent Name="UserB">
		<Property Name = "speaksEnglish" Value="False"/>
		<Property Name = "speaksChinese" Value="True"/>		
	</Agent>

	<Object Name="Vase">
		<Property Name = "onTable"  Value="True" />
		<Property Name = "hasWater"  Value="True" />
		<Property Name = "broken"  Value="False" />		
	</Object>

	<Object Name="Cake">
		<Property Name = "onTable"  Value="True" />
		<Property Name = "chocolate"  Value="True" />
	</Object>

</WorldModel>
